/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author USER
 */
public class busqueda extends javax.swing.JFrame {

    /**
     * Creates new form busqueda
     */
    public busqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnbus1 = new javax.swing.JButton();
        btnbus2 = new javax.swing.JButton();
        btnbus3 = new javax.swing.JButton();
        btnbus4 = new javax.swing.JButton();
        btnbus5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnbus1.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        btnbus1.setText("Encontrar clientes menores de edad");

        btnbus2.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        btnbus2.setText("Encontrar paises mas visitados");

        btnbus3.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        btnbus3.setText("Encontrar clientes con mas compras");

        btnbus4.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        btnbus4.setText("Encontrar agente con mayor numero de Ventas");

        btnbus5.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        btnbus5.setText("Cantidad de viajes clientes mayores de edad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbus3)
                            .addComponent(btnbus1))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnbus2)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbus5)
                            .addComponent(btnbus4))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnbus1)
                .addGap(18, 18, 18)
                .addComponent(btnbus2)
                .addGap(18, 18, 18)
                .addComponent(btnbus3)
                .addGap(18, 18, 18)
                .addComponent(btnbus4)
                .addGap(18, 18, 18)
                .addComponent(btnbus5)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbus1;
    public javax.swing.JButton btnbus2;
    public javax.swing.JButton btnbus3;
    public javax.swing.JButton btnbus4;
    public javax.swing.JButton btnbus5;
    // End of variables declaration//GEN-END:variables
}
